export default {
    CHANGE_THERE_COLOR: "CHANGE_THERE_COLOR",

    SHOW_THEME_VIEW:"SHOW_THEME_VIEW",

    POPUL_LOADING: "POPUL_LODAING",
    POPUL_LOADING_FAIL: "POPUL_LODAING_FAIL",
    POPUL_LOADING_SUCCESS: "POPUL_LODAING_SUCCESS",
    POPUL_LOAD_MORE_SUCCESS: "POPUL_LOAD_MORE_SUCCESS",
    POPUL_LOAD_MORE_FAIL: "POPUL_LOAD_MORE_FAIL",

    FLUSH_POPULAR_FAVORITE: "FLUSH_POPULAR_FAVORITE",

    TRENDING_FLUSH_FAVORITE: "TRENDING_FLUSH_FAVORITE",
    TRENDING_REFRESH: "TRENDING_REFRESH",
    TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
    TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
    TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",

    FAVORITE_LOAD_DATA: "FAVORITE_LOAD_DATA",
    FAVORITE_LOAD_SUCCESS: "FAVORITE_LOAD_SUCCESS",
    FAVORITE_LOAD_FAIL: "FAVORITE_LOAD_FAIL",

    LANGUAGE_LOAD_SUCCESS: "LANGUAGE_LOAD_SUCCESS",

    SEARCH_LOAD_MORE_SUCCESS:"SEARCH_LOAD_MORE_SUCCESS",
    SEARCH_LOAD_MORE_FAIL:"SEARCH_LOAD_MORE_FAIL",
    SEARCH_REFRESH:"SEARCH_REFRESH",
    SEARCH_CANCEL:"SEARCH_CANCEL",
    SEARCH_FAIL:"SEARCH_FAIL",
    SEARCH_REFRESH_SUCCESS:"SEARCH_REFRESH_SUCCESS",
};

