# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo3
#Umeng公共基础
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCCommonLog'
# 统计
  pod 'UMCAnalytics'
  end
